name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 26.3
        include:
          - emacs_version: 26.3
            lint_ignore: 1
    env:
      EMACS_LINT_IGNORE: ${{ matrix.lint_ignore }}
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version ${{ matrix.emacs_version }}

      - uses: actions/checkout@v2
      - name: Run tests
        run: "make all"
